### ISSUE TITLE
Adding rootmode option to FileCase

### ISSUE THREAD

**Issue by ruditimmermans** [CepiPerez/filecase-sailfish#30]
Mebay this would be a nice idea to add a rootmode option to FIleCase like NanoFiles has...

https://github.com/Michal-Szczepaniak/nanofiles/search?q=root

**Comment by Olf0** [comment]
A "root mode" is nice, but dangerous.  In my opinion, one should use the command line for working as root user, because that makes one more aware of the fact that any misstep could break the SailfishOS installation.  In "root mode" one is even able to brick a device permanently (by altering or deleting the "right" files).

But if you want to pursue this: Go for it!  It just should be an option at the very bottom of the settings page in an "Expert" section with a big disclaimer "Enables you to brick your device!".
And it should provide some indicator in the main page when "root mode" is on; otherwise people will forget that they switched it on and permanently use "root mode".

But OTOH, I think this Patch for Patchmanager is still working: https://openrepos.net/content/schturman/startasroot-filecase
Can you please try it, first.  It may also provide an easier approach (unpack the RPM with midnight commander or look at the patch file when it is installed).  An I like the fact, that it provides a separate icon at the launcher, so one can always start FileCase in root or non-root mode.

**Comment by ruditimmermans** [comment]
Yes you are write on this, i will make a speperate app then you can FileCase as root, i dont use the Patch and the other system patch from Schturman dont works anymore....

I close this ;)

**Comment by Olf0** [comment]
But IMO a separate app is absolute overkill.  The "StartAsRoot-FileCase" Patch by Schturman is doing the right thing: It provides another icon at the launcher and starts FileCase in "root mode".

The fact that other Patches from him are nor working any more does not tell anything about this one!  And even if it fails, it should be easy to fix that, because it is not even really a few lines of code; basically just a `.desktop` file.

**Comment by ruditimmermans** [comment]
I dont use patches as it brakes easy sfos, anyway this is what i think about it patchmanager is not a run for me, anyway it's not a easy desktop file but a some script code i talked a few years back with him about his system patch, but it's only formyself not for releasing ;) Anyway i have it already running on my system one i made myself ;)

**Comment by ruditimmermans** [comment]
Hi Olf0,

I one let you know that i'm quit with Sailfish OS, i moved to a minimalistic e-inkt phone Kingrow K1, this means i'm not do any development anymore on Sfos as this os is not what i'm look for and i one sell my Sony device also. so just let you know. So the best with your develpment on Sailfish OS, but for me it's time to go.

**Comment by Olf0** [comment]
Oh, that is unfortunate!
Well, then good bye and better luck with your Kingrow K1.
